BEGIN ut_trace.trace('********************Comenzar proceso de objeto:JPMDR******************************'); END;
/
DECLARE
clXml CLOB;

BEGIN
clXml := '<?xml version="1.0" encoding="WINDOWS-1252"?>
<APPLICATION>
  <INFO>
    <NAME>JPMDR</NAME>
    <DISPLAY>Relación de clientes, cupos y planes</DISPLAY>
    <AUTHOR>OpenSystems</AUTHOR>
    <TYPE>MD</TYPE>
    <MODULE>OR</MODULE>
    <SITE>
      <APPLICATION>JPPCL</APPLICATION>
      <QUERY>1ffbf9fd-d4db-4c7d-a5c9-e9826ac5b920</QUERY>
    </SITE>
    <HELP/>
  </INFO>
  <VIEW>
    <TABVIEW>
      <TABNAME>Clientes SILOKO</TABNAME>
      <INFOCLASS>0</INFOCLASS>
      <POSLEVEL>0,0</POSLEVEL>
      <GRANT>U</GRANT>
      <DISPLAYTYPE>G</DISPLAYTYPE>
      <TABATTRIBUTE>
        <NAME>CUSTOMER_ID</NAME>
        <SEQUENCE>SEQ_OR_JPB_CUSTOMER_372677</SEQUENCE>
        <POSITION>0</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>DESCRIPTION</NAME>
        <POSITION>1</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>DOCUMENT</NAME>
        <POSITION>2</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>STRATUM_ID</NAME>
        <POSITION>3</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>REGISTRATION_DATE</NAME>
        <POSITION>4</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>HAS_QUOTA</NAME>
        <POSITION>5</POSITION>
      </TABATTRIBUTE>
      <DATA>
        <NAME>OR_JPB_CUSTOMER</NAME>
        <MODEL>
          <ENTITY>
            <NAME>OR_JPB_CUSTOMER</NAME>
            <ATTRIBUTE>
              <NAME>CUSTOMER_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>true</KEY>
              <LENGTH>15</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>DESCRIPTION</NAME>
              <TYPE>Varchar</TYPE>
              <KEY>false</KEY>
              <LENGTH>60</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>DOCUMENT</NAME>
              <TYPE>Varchar</TYPE>
              <KEY>false</KEY>
              <LENGTH>12</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>STRATUM_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>false</KEY>
              <LENGTH>4</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>REGISTRATION_DATE</NAME>
              <TYPE>Date</TYPE>
              <KEY>false</KEY>
              <LENGTH>7</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>HAS_QUOTA</NAME>
              <TYPE>Varchar</TYPE>
              <KEY>false</KEY>
              <LENGTH>2</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>true</ISNULL>
            </ATTRIBUTE>
          </ENTITY>
        </MODEL>
        <VIEW>
          <NAME>OR_JPB_CUSTOMER</NAME>
          <DISPLAY>Clientes SILOKO</DISPLAY>
          <SINGULARDISPLAY>Cliente SILOKO</SINGULARDISPLAY>
          <GROUP>
            <PARAMETER>
              <NAME>CUSTOMER_ID</NAME>
              <DISPLAY>ID</DISPLAY>
              <TOOLTIP>Identificador del cliente SILOKO.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>DESCRIPTION</NAME>
              <DISPLAY>Cliente SILOKO</DISPLAY>
              <TOOLTIP>Nombre del cliente SILOKO.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
              <REPRESENTATIVE>1</REPRESENTATIVE>
            </PARAMETER>
            <PARAMETER>
              <NAME>DOCUMENT</NAME>
              <DISPLAY>Doc. de identidad</DISPLAY>
              <TOOLTIP>Código o número de identidad.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>STRATUM_ID</NAME>
              <DISPLAY>Estrato</DISPLAY>
              <TOOLTIP>Identificador del estrato del cliente.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>REGISTRATION_DATE</NAME>
              <DISPLAY>Fecha de registro</DISPLAY>
              <TOOLTIP>Fecha de registro del cliente SILOKO.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>HAS_QUOTA</NAME>
              <DISPLAY>¿Tiene cupo?</DISPLAY>
              <TOOLTIP>¿Tiene cupo? (YN).</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>false</REQUIRED>
              <VISIBLE>false</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
          </GROUP>
        </VIEW>
        <CTRL>
          <NAME>OR_JPB_CUSTOMER</NAME>
          <PARAMETERS>
            <NAME>CUSTOMER_ID</NAME>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>DESCRIPTION</NAME>
            <COMPONENT>
              <TYPE>NLOV</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>DOCUMENT</NAME>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>STRATUM_ID</NAME>
            <COMPONENT>
              <TYPE>NLOV</TYPE>
              <SOURCE>
                <NAME>STRATUM_ID</NAME>
                <MODEL>
                  <ENTITY>
                    <NAME>5ec07cee-da2b-4b66-b41c-2209195cdb60</NAME>
                    <ATTRIBUTE>
                      <NAME>ID</NAME>
                      <TYPE>Number</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>4</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>false</ISNULL>
                    </ATTRIBUTE>
                    <ATTRIBUTE>
                      <NAME>DESCRIPTION</NAME>
                      <TYPE>Varchar</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>100</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>false</ISNULL>
                    </ATTRIBUTE>
                  </ENTITY>
                  <PROXY>
                    <NAME>STRATUM_ID</NAME>
                    <ENTITY>OR_JPB_CUSTOMER</ENTITY>
                    <SOURCE>SELECT
	OR_JPB_STRATUM.STRATUM_ID ID,
	OR_JPB_STRATUM.DESCRIPTION DESCRIPTION
FROM
	OR_JPB_STRATUM
ORDER BY
	OR_JPB_STRATUM.DESCRIPTION</SOURCE>
                    <TYPE>Statement</TYPE>
                  </PROXY>
                </MODEL>
                <VIEW>
                  <NAME>STRATUM_ID</NAME>
                  <DISPLAY>Estrato</DISPLAY>
                  <ATTRIBUTE>
                    <NAME>ID</NAME>
                    <DISPLAY>ID</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                  <ATTRIBUTE>
                    <NAME>DESCRIPTION</NAME>
                    <DISPLAY>Estrato</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                </VIEW>
              </SOURCE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>REGISTRATION_DATE</NAME>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>HAS_QUOTA</NAME>
            <COMPONENT>
              <TYPE>NLOV</TYPE>
            </COMPONENT>
          </PARAMETERS>
        </CTRL>
      </DATA>
    </TABVIEW>
    <TABVIEW>
      <TABNAME>Planes</TABNAME>
      <INFOCLASS>0</INFOCLASS>
      <POSLEVEL>1,0</POSLEVEL>
      <PARENT>OR_JPB_CUSTOMER</PARENT>
      <JOIN> OR_JPB_PLAN.CUSTOMER_ID = OR_JPB_CUSTOMER.CUSTOMER_ID </JOIN>
      <GRANT>CRUD</GRANT>
      <DISPLAYTYPE>G</DISPLAYTYPE>
      <TABATTRIBUTE>
        <NAME>PLAN_ID</NAME>
        <SEQUENCE>SEQ_OR_JPB_PLAN_372673</SEQUENCE>
        <POSITION>0</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>CUSTOMER_ID</NAME>
        <POSITION>1</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>IS_ACTIVE</NAME>
        <POSITION>2</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>PLAN_TYPE_ID</NAME>
        <POSITION>3</POSITION>
      </TABATTRIBUTE>
      <DATA>
        <NAME>OR_JPB_PLAN</NAME>
        <MODEL>
          <ENTITY>
            <NAME>OR_JPB_PLAN</NAME>
            <ATTRIBUTE>
              <NAME>PLAN_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>true</KEY>
              <LENGTH>15</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>CUSTOMER_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>false</KEY>
              <LENGTH>15</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>IS_ACTIVE</NAME>
              <TYPE>Varchar</TYPE>
              <KEY>false</KEY>
              <LENGTH>100</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>PLAN_TYPE_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>false</KEY>
              <LENGTH>4</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
          </ENTITY>
        </MODEL>
        <VIEW>
          <NAME>OR_JPB_PLAN</NAME>
          <DISPLAY>Planes</DISPLAY>
          <SINGULARDISPLAY>Plan</SINGULARDISPLAY>
          <GROUP>
            <PARAMETER>
              <NAME>PLAN_ID</NAME>
              <DISPLAY>Código del plan</DISPLAY>
              <TOOLTIP>Código del plan asociado al cliente.</TOOLTIP>
              <READONLY>false</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
              <REPRESENTATIVE>1</REPRESENTATIVE>
            </PARAMETER>
            <PARAMETER>
              <NAME>CUSTOMER_ID</NAME>
              <DISPLAY>Cliente SILOKO</DISPLAY>
              <TOOLTIP>Identificador del cliente SILOKO.</TOOLTIP>
              <READONLY>false</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>false</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>IS_ACTIVE</NAME>
              <DISPLAY>¿Plan activo?</DISPLAY>
              <TOOLTIP>Indicador de actividad del plan (YN).</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>PLAN_TYPE_ID</NAME>
              <DISPLAY>Tipo de plan</DISPLAY>
              <TOOLTIP>Identificador del tipo de plan.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
          </GROUP>
        </VIEW>
        <CTRL>
          <NAME>OR_JPB_PLAN</NAME>
          <PARAMETERS>
            <NAME>PLAN_ID</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>CUSTOMER_ID</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>IS_ACTIVE</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>NLOV</TYPE>
              <SOURCE>
                <NAME>IS_ACTIVE</NAME>
                <MODEL>
                  <ENTITY>
                    <NAME>7d44d675-f452-45f4-ac00-42be099c6cda</NAME>
                    <ATTRIBUTE>
                      <NAME>ID</NAME>
                      <TYPE>Varchar</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>100</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>true</ISNULL>
                    </ATTRIBUTE>
                    <ATTRIBUTE>
                      <NAME>DESCRIPTION</NAME>
                      <TYPE>Varchar</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>100</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>false</ISNULL>
                    </ATTRIBUTE>
                  </ENTITY>
                  <PROXY>
                    <NAME>IS_ACTIVE</NAME>
                    <ENTITY>OR_JPB_PLAN</ENTITY>
                    <SOURCE>SELECT
	GE_DOMAIN_VALUES.VALUE ID,
	GE_DOMAIN_VALUES.DESCRIPTION DESCRIPTION
FROM
	GE_DOMAIN_VALUES
WHERE
	GE_DOMAIN_VALUES.DOMAIN = 60066
</SOURCE>
                    <TYPE>Statement</TYPE>
                  </PROXY>
                </MODEL>
                <VIEW>
                  <NAME>IS_ACTIVE</NAME>
                  <DISPLAY>¿Plan activo?</DISPLAY>
                  <ATTRIBUTE>
                    <NAME>ID</NAME>
                    <DISPLAY>ID</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                  <ATTRIBUTE>
                    <NAME>DESCRIPTION</NAME>
                    <DISPLAY>Opción</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                </VIEW>
              </SOURCE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>PLAN_TYPE_ID</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>NLOV</TYPE>
              <SOURCE>
                <NAME>PLAN_TYPE_ID</NAME>
                <MODEL>
                  <ENTITY>
                    <NAME>07e60364-aa07-48f8-bf64-ea8b5645a141</NAME>
                    <ATTRIBUTE>
                      <NAME>ID</NAME>
                      <TYPE>Number</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>4</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>false</ISNULL>
                    </ATTRIBUTE>
                    <ATTRIBUTE>
                      <NAME>DESCRIPTION</NAME>
                      <TYPE>Varchar</TYPE>
                      <KEY>false</KEY>
                      <LENGTH>100</LENGTH>
                      <SCALE>0</SCALE>
                      <ISNULL>false</ISNULL>
                    </ATTRIBUTE>
                  </ENTITY>
                  <PROXY>
                    <NAME>PLAN_TYPE_ID</NAME>
                    <ENTITY>OR_JPB_PLAN</ENTITY>
                    <SOURCE>SELECT
	OR_JPB_PLAN_TYPE.PLAN_TYPE_ID ID,
	OR_JPB_PLAN_TYPE.DESCRIPTION DESCRIPTION
FROM
	OR_JPB_PLAN_TYPE
ORDER BY
	OR_JPB_PLAN_TYPE.DESCRIPTION</SOURCE>
                    <TYPE>Statement</TYPE>
                  </PROXY>
                </MODEL>
                <VIEW>
                  <NAME>PLAN_TYPE_ID</NAME>
                  <DISPLAY>Tipo de plan</DISPLAY>
                  <ATTRIBUTE>
                    <NAME>ID</NAME>
                    <DISPLAY>ID</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                  <ATTRIBUTE>
                    <NAME>DESCRIPTION</NAME>
                    <DISPLAY>Tipo de plan</DISPLAY>
                    <VISIBLE>true</VISIBLE>
                  </ATTRIBUTE>
                </VIEW>
              </SOURCE>
            </COMPONENT>
          </PARAMETERS>
        </CTRL>
      </DATA>
    </TABVIEW>
    <TABVIEW>
      <TABNAME>Cupos</TABNAME>
      <INFOCLASS>0</INFOCLASS>
      <POSLEVEL>1,1</POSLEVEL>
      <PARENT>OR_JPB_CUSTOMER</PARENT>
      <JOIN> OR_JPB_ASSIGNED_QUOTA.CUSTOMER_ID = OR_JPB_CUSTOMER.CUSTOMER_ID </JOIN>
      <GRANT>CRUD</GRANT>
      <DISPLAYTYPE>G</DISPLAYTYPE>
      <TABATTRIBUTE>
        <NAME>QUOTA_ID</NAME>
        <SEQUENCE>SEQ_OR_JPB_ASSIGNED_QUO_372769</SEQUENCE>
        <POSITION>0</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>CUSTOMER_ID</NAME>
        <POSITION>1</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>ASSIGNED</NAME>
        <POSITION>2</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>AVAILABLE</NAME>
        <POSITION>3</POSITION>
      </TABATTRIBUTE>
      <TABATTRIBUTE>
        <NAME>IS_ENABLED</NAME>
        <POSITION>4</POSITION>
      </TABATTRIBUTE>
      <DATA>
        <NAME>OR_JPB_ASSIGNED_QUOTA</NAME>
        <MODEL>
          <ENTITY>
            <NAME>OR_JPB_ASSIGNED_QUOTA</NAME>
            <ATTRIBUTE>
              <NAME>QUOTA_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>true</KEY>
              <LENGTH>15</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>CUSTOMER_ID</NAME>
              <TYPE>Number</TYPE>
              <KEY>false</KEY>
              <LENGTH>15</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>ASSIGNED</NAME>
              <TYPE>Decimal</TYPE>
              <KEY>false</KEY>
              <LENGTH>20</LENGTH>
              <SCALE>4</SCALE>
              <ISNULL>true</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>AVAILABLE</NAME>
              <TYPE>Decimal</TYPE>
              <KEY>false</KEY>
              <LENGTH>20</LENGTH>
              <SCALE>4</SCALE>
              <ISNULL>true</ISNULL>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>IS_ENABLED</NAME>
              <TYPE>Varchar</TYPE>
              <KEY>false</KEY>
              <LENGTH>100</LENGTH>
              <SCALE>0</SCALE>
              <ISNULL>false</ISNULL>
            </ATTRIBUTE>
          </ENTITY>
        </MODEL>
        <VIEW>
          <NAME>OR_JPB_ASSIGNED_QUOTA</NAME>
          <DISPLAY>Cupos</DISPLAY>
          <SINGULARDISPLAY>Cupo</SINGULARDISPLAY>
          <GROUP>
            <PARAMETER>
              <NAME>QUOTA_ID</NAME>
              <DISPLAY>ID</DISPLAY>
              <TOOLTIP>Identificador del cupo asignado.</TOOLTIP>
              <READONLY>false</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
              <REPRESENTATIVE>1</REPRESENTATIVE>
            </PARAMETER>
            <PARAMETER>
              <NAME>CUSTOMER_ID</NAME>
              <DISPLAY>Cliente SILOKO</DISPLAY>
              <TOOLTIP>Identificador de SILOKO.</TOOLTIP>
              <READONLY>false</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>false</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>ASSIGNED</NAME>
              <DISPLAY>Monto asignado</DISPLAY>
              <TOOLTIP>Monto asignado en el cupo.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>false</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>AVAILABLE</NAME>
              <DISPLAY>Monto disponible</DISPLAY>
              <TOOLTIP>Monto disponible en el cupo.</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>false</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
            <PARAMETER>
              <NAME>IS_ENABLED</NAME>
              <DISPLAY>¿Habilitado?</DISPLAY>
              <TOOLTIP>¿Habilitado? (YN).</TOOLTIP>
              <READONLY>true</READONLY>
              <REQUIRED>true</REQUIRED>
              <VISIBLE>true</VISIBLE>
              <STYLECASE>Upper</STYLECASE>
            </PARAMETER>
          </GROUP>
        </VIEW>
        <CTRL>
          <NAME>OR_JPB_ASSIGNED_QUOTA</NAME>
          <PARAMETERS>
            <NAME>QUOTA_ID</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>CUSTOMER_ID</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>ASSIGNED</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>AVAILABLE</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
          <PARAMETERS>
            <NAME>IS_ENABLED</NAME>
            <PARENT>OR_JPB_CUSTOMER</PARENT>
            <COMPONENT>
              <TYPE>Textbox</TYPE>
            </COMPONENT>
          </PARAMETERS>
        </CTRL>
      </DATA>
    </TABVIEW>
  </VIEW>
</APPLICATION>
';
ge_boapplication.Save(clXml);
commit;
exception when others then
rollback;
ut_trace.trace('||**ERROR:'|| sqlerrm);
raise;
END;
/
BEGIN ut_trace.trace('********************FIN  proceso de objeto:JPMDR******************************'); end;
/
